SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 FactionColor 0.251 0 0.502 1
 m_OutlineFactionColor 0.318 0.071 0.561 1
 m_NotificationFactionColor 0.392 0.157 0.624 1
 m_NotificationTextFactionColor 0.083 0 0.159 1
}